server:
  port: 8083

spring:
  application:
     name: course-service
  datasource:
    url: jdbc:mysql://localhost:3306/course_db?serverTimezone=UTC
    username: root
    password: sql
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true