server:
  port: 8084

spring:
  application:
    name: grade-service
  datasource:
    url: jdbc:mysql://localhost:3306/grade_db?serverTimezone=UTC
    username: root
    password: sql
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true